routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');
});

Route::get('/app', function () {
    return view('welcome');
});

Route::get('/order', 'HomeController@order')->name('order');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/how-it-works', 'HomeController@howItWorks')->name('hiw');
Route::get('/sample', 'HomeController@sample')->name('samples');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/pricing', 'HomeController@pricing')->name('pricing');
Route::get('/about', 'HomeController@about')->name('about');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin\\'], function (){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('subjects', 'SubjectsController');
    Route::resource('orders', 'OrdersController');
    Route::resource('academic_levels', 'AccademicLevelsController');
    Route::resource('logs', 'LogsController');
    Route::resource('work_types', 'WorkTypesController');
    Route::resource('customers', 'CustomersController');
    Route::resource('citation_styles', 'CitationStylesController');
});

app/Http/Controllers/Admin/WorkTypesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\WorkType;
use Illuminate\Http\Request;

class WorkTypesController extends Controller
{

    protected $worktypes;

    public function __construct(WorkType  $workType)
    {
        $this->worktypes = $workType;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = $this->worktypes->newQuery()
            ->get();

        return view('admin.work_type.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.work_type.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:work_types',
            'status' => 'required'
        ]);

        $this->worktypes->newQuery()
            ->create($request->except("_token"));

        return redirect()->route('admin.work_types.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/work_type/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="content-wrapper">
        <div class="content-header row"></div>
        <div class="content-body">
            <section id="worktype-index">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                {{ __('All Work Types') }}
                                <a href="{{ route('admin.work_types.index') }}" class="btn btn-light-primary">Types</a>
                            </div>
                            <div class="card-body">
                                <form action="{{ route('admin.work_types.store') }}" method="POST">
                                    @csrf
                                    <div class="form-group">
                                        <label for="name">Name: </label>
                                        <input class="form-control" id="name" name="name" value="{{ old('name') }}">
                                    </div>
                                    <div class="form-group">
                                        <label for="status">Status: </label>
                                        <select class="form-control" id="status" name="status">
                                            <option value="active"> Active </option>
                                            <option value="inactive">Inactive </option>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-light-primary">Add Type</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

@endsection

resources/views/admin/work_type/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="content-wrapper">
        <div class="content-header row"></div>
        <div class="content-body">
            <section id="worktype-index">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                {{ __('All Work Types') }}
                                <a href="{{ route('admin.work_types.create') }}" class="btn btn-light-primary">Add Type</a>
                            </div>
                            <div class="card-body">
                                <div class="table-bordered table-striped">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>#ID</th>
                                            <th>Name</th>
                                            <th>Status</th>
                                            <th>Created At</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($data as $datum)
                                        <tr>
                                            <td>{{ $datum->id }}</td>
                                            <td>{{ $datum->name }}</td>
                                            <td>{{ $datum->status }}</td>
                                            <td>{{ \Carbon\Carbon::parse($datum->created_at)->diffForHumans() }}</td>
                                            <td>

                                            </td>
                                        </tr>
                                        @endforeach
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/admin/work_type/show.blade.php
@extends('layouts.admin')

@section('content')

@endsection