routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');
});

Route::get('/app', function () {
    return view('welcome');
});

Route::get('/order', 'HomeController@order')->name('order');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/how-it-works', 'HomeController@howItWorks')->name('hiw');
Route::get('/sample', 'HomeController@sample')->name('samples');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/pricing', 'HomeController@pricing')->name('pricing');
Route::get('/about', 'HomeController@about')->name('about');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin\\'], function (){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('subjects', 'SubjectsController');
    Route::resource('orders', 'OrdersController');
    Route::resource('academic_levels', 'AccademicLevelsController');
    Route::resource('logs', 'LogsController');
    Route::resource('work_types', 'WorkTypesController');
    Route::resource('customers', 'CustomersController');
    Route::resource('citation_styles', 'CitationStylesController');
});

app/Models/CitationStyle.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CitationStyle extends Model
{
    protected $table = 'citation_styles';

    protected $fillable = [
        'name',
        'status'
    ];

    public function order()
    {
        return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/Admin/CitationStylesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\CitationStyle;
use Illuminate\Http\Request;

class CitationStylesController extends Controller
{
    protected $citations;

    public function __construct(CitationStyle  $citations)
    {
        $this->citations = $citations;
    }

    public function index()
    {
        $data = $this->citations->newQuery()
            ->get();
        return view('admin.citation_style.index', compact('data'));
    }

    public function create()
    {
        return view('admin.citation_style.create');
    }

    public function store(Request  $request)
    {

    }

    public function edit($id)
    {

    }

    public function update($id, Request $request)
    {

    }

    public function destroy($id)
    {

    }
}

resources/views/admin/citation_style/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="content-wrapper">
        <div class="content-header row"></div>
        <div class="content-body">
            <section id="worktype-index">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                {{ __('All Work Types') }}
                                <a href="{{ route('admin.citation_styles.create') }}" class="btn btn-light-primary">Add Type</a>
                            </div>
                            <div class="card-body">
                                <div class="table-bordered table-striped">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>#ID</th>
                                            <th>Name</th>
                                            <th>Status</th>
                                            <th>Created At</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($data as $datum)
                                            <tr>
                                                <td>{{ $datum->id }}</td>
                                                <td>{{ $datum->name }}</td>
                                                <td>{{ $datum->status }}</td>
                                                <td>{{ \Carbon\Carbon::parse($datum->created_at)->diffForHumans() }}</td>
                                                <td>

                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection